### PR TITLE
Added options parameter to support prefix. We want to be able to add prefix like 'hostname'.

### PR DESCRIPTION
**Pull request by Mityo**

### CODE REVIEW

**Comment by nemtsov** [comment]
Thank you for your contribution; this is great!
I'm not quite sure about the position of the prefix. I like the idea of adding arbitrary metadata, but the location (where to put the prefix) is contentious: why is it after the timestamp and not after the namespace or why not after the level? I think a flexible way to implement this would be to allow a string to be used for formatting, e.g.,  `:timestamp: my_prefix_1 my_prefix_2 (:namespace:) :LEVEL:: :data:`. What do you think?

**Comment by Mityo** [comment]
Formatting the output with a string sounds great to me.

**Comment by nemtsov** [comment]
Great! Are you interested in implementing this? The challenge would be to make this as efficient as possible so that logging doesn't become unnecessarily slow.

**Comment by Mityo** [comment]
Yep. I'll try to find an efficient way to implement it.

**Comment by nemtsov** [comment]
closing in favor of https://github.com/dowjones/namespaced-console-logger/pull/4

**Pull request closed without merging**
